In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
import plotly.graph_objects as go
import plotly.express as px
import matplotlib.pyplot as plt
from datetime import date
import interpolation_module as interp

2023-10-09 14:22:50.107177: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-10-09 14:22:50.108513: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-09 14:22:50.131652: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-09 14:22:50.132376: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-09 14:22:50.519096: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
#import data and prepare columns
pm10_data = pd.read_csv("../../data/milano_pollutants_data/pm10_daily.csv", index_col=0)
pm10_data = pm10_data.rename(columns={'value': 'pm_10'})

meteo_data = pd.read_csv("../../data/milano_meteo_data/meteo_data_merged_daily.csv", index_col=0)

topo_data = pd.read_csv("../../data/milano_topo_data/topo_meteo_pm10_stations.csv", index_col=0)

In [3]:
pm10_data

             date  sensor_id        lat       lng  pm_10
0      1998-02-14       6905  45.473226  9.222315  133.0
1      1998-02-15       6905  45.473226  9.222315   80.0
2      1998-02-16       6905  45.473226  9.222315  104.0
3      1998-02-17       6905  45.473226  9.222315   39.0
4      1998-02-18       6905  45.473226  9.222315   58.0
...           ...        ...        ...       ...    ...
66045  2023-02-05       6908  45.483630  9.327360   20.0
66046  2023-02-05       6912  45.462416  8.880210   19.0
66047  2023-02-05       6956  45.463347  9.195325   14.0
66048  2023-02-05      10273  45.478996  9.235491   14.0
66049  2023-02-05      10320  45.470499  9.197460   22.0

[66050 rows x 5 columns]

In [4]:
meteo_data

,date,lat,stationID,lng,temperature,precipitation,humidity,global_radiation,hydrometric_level,N,NE,E,SE,S,SW,W,NW
0,1989-01-01,45.496316,501,9.190934,4.569565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1989-01-01,45.473226,502,9.222315,4.686364,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1989-01-01,45.476063,503,9.141786,5.208696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1989-01-02,45.496316,501,9.190934,4.162500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1989-01-02,45.473226,502,9.222315,4.161905,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162114,2022-03-17,45.613692,513,9.508122,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.3,0.0,0.0,0.0,0.0,0.0
162115,2022-03-17,45.436109,525,9.097411,NaN,NaN,NaN,NaN,NaN,0.0,0.7,0.0,0.0,0.0,0.0,0.0,0.0
162116,2022-03-17,45.324517,535,9.134517,NaN,NaN,NaN,NaN,NaN,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162117,2022-03-17,45.517286,1547,9.091610,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.4,0.0,0.0,0.0,0.0,0.0
162118,2022-03-17,45.394655,1873,8.889706,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.9

In [5]:
topo_data

,lng,geometry,utm_x,utm_y,dtm_milan,aspect,hillshade,ndvi_2019,plan_curvature,profile_curvature,...,lc_12,lc_14,lc_21,lc_22,lc_23,lc_31,lc_32,lc_33,lc_41,lc_51
lat,,,,,,,,,,,,,,,,,,,,,
45.496316,9.190934,POINT (514918.0348613303 5038104.95079348),514918.034861,5.038105e+06,127.29200,27.936516,181.0,0.272276,-1.300626,1.143405,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.473226,9.222315,POINT (517376.9890661904 5035546.032345283),517376.989066,5.035546e+06,116.71500,13.152611,181.0,0.186676,0.257332,0.093392,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.476063,9.141786,POINT (511081.97919612186 5035846.954957355),511081.979196,5.035847e+06,123.95150,210.222600,180.0,0.229072,0.060926,-0.032580,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.471656,9.189110,POINT (514781.97008367797 5035364.967350351),514781.970084,5.035365e+06,120.77182,21.154236,181.0,0.080548,-0.060938,0.011816,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.502064,9.265130,POINT (520713.00060529384 5038759.991719732),520713.000605,5.038760e+06,121.87100,16.726921,184.0,0.161998,-0.317691,-0.789706,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.436109,9.097411,POINT (507619.0123021142 5031403.0544401435),507619.012302,5.031403e+06,117.22500,241.323070,182.0,0.222366,0.169710,-0.426268,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.582803,9.158975,POINT (512401.9894888513 5047708.033186275),512401.989489,5.047708e+06,171.00100,252.825800,182.0,0.349899,0.146917,0.910772,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.491633,9.248738,POINT (519435.98122683645 5037597.04262049),519435.981227,5.037597e+06,117.37800,100.147835,138.0,0.096197,0.176462,1.092477,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
45.324517,9.134517,POINT (510541.9793715059 5019009.954099943),510541.979372,5.019010e+06,96.00600,343.530730,183.0,0.351973,0.917555,-0.850358,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.472580,9.353497,POINT (527630.9890585921 5035510.996818309),527630.989059,5.035511e+06,110.82576,170.765690,180.0,0.485481,-0.000833,-0.000711,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.613692,9.508122,POINT (539617.9621003175 5051253.026559712),539617.962100,5.051253e+06,197.74878,46.003500,180.0,0.340839,0.017968,-0.017066,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.171919,9.488997,POINT (538425.0127104069 5002165.00462999),538425.012710,5.002165e+06,140.39348,156.586060,168.0,0.625454,0.304617,-0.824899,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
45.496780,9.257515,POINT (520119.9687097578 5038171.019447793),520119.968710,5.038171e+06,120.36700,84.649254,180.0,0.257589,-0.039992,0.200060,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.542665,9.205603,POINT (516050.96773290966 5043257.035645699),516050.967733,5.043257e+06,145.39200,243.985900,182.0,0.638978,-0.220508,0.743542,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.548517,8.847322,POINT (488082.0054498212 5043897.96028009),488082.005450,5.043898e+06,183.26503,311.262500,182.0,0.444127,-0.087728,0.620219,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.281956,8.988563,POINT (499103.0214238888 5014272.97806337),499103.021424,5.014273e+06,98.45092,134.017230,179.0,0.151740,-0.640004,0.464671,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.487068,9.193231,POINT (515099.97488338605 5037077.955589348),515099.974883,5.037078e+06,124.01400,175.174200,177.0,0.214884,0.300034,-3.375961,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.490073,9.194355,POINT (515187.0019340352 5037412.013500625),515187.001934,5.037412e+06,122.57700,317.266480,199.0,0.068879,0.690355,0.414263,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.359261,9.202665,POINT (515872.96664379176 5022880.978767454),515872.966644,5.022881e+06,89.15700,147.178050,180.0,0.495172,-0.177991,-0.217969,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
45.525802,9.192224,POINT (515010.98473891185 5041381.006080905),515010.984739,5.041381e+06,134.24600,96.272030,130.0,0.430877,-0.947877,13.016112,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.583137,9.157733,POINT (512305.0253759183 5047744.9488825435),512305.025376,5.047745e+06,167.31800,356.273620,212.0,0.424589,-0.372431,11.383672,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.574091,9.048190,POINT (503759.9894135607 5046728.981935093),503759.989414,5.046729e+06,178.88900,46.727257,176.0,0.507127,2.477135,-7.047035,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
45.535577,9.005200,POINT (500406.0034281213 5042449.031190111),500406.003428,5.042449e+06,160.79900,330.211300,183.0,0.323956,0.554676,-1.001232,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.607845,8.952897,POINT (496327.02527925046 5050478.962769082),496327.025279,5.050479e+06,212.41800,80.684300,158.0,0.652380,-0.485496,0.278542,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.517811,9.087923,POINT (506866.97652709536 5040479.0169942565),506866.976527,5.040479e+06,144.45800,34.492220,184.0,0.126131,4.603513,-3.760379,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.517286,9.091610,POINT (507155.00573620084 5040421.012728752),507155.005736,5.040421e+06,142.56800,25.495697,182.0,0.082585,-0.136125,0.059981,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.458065,8.854409,POINT (488617.00052616885 5033847.972911869),488617.000526,5.033848e+06,136.08200,165.539950,180.0,0.365746,1.786984,-1.885013,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.378272,9.192426,POINT (515065.9880721329 5024991.029398677),515065.988072,5.024991e+06,95.82000,210.999910,162.0,0.401843,2.072145,-13.279845,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
45.394655,8.889706,POINT (491367.02844128635 5026799.005487748),491367.028441,5.026799e+06,111.55300,326.481800,233.0,0.493541,-0.058654,1.617340,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.483630,9.327360,POINT (525582.9975641342 5036729.960745652),525582.997564,5.036730e+06,115.14709,118.279170,178.0,0.477863,-0.038144,-0.038113,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.462416,8.880210,POINT (490634.9661733646 5034328.023256964),490634.966173,5.034328e+06,137.83680,152.473100,180.0,0.694880,-0.001013,0.001124,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.463347,9.195325,POINT (515270.0149659513 5034443.028846752),515270.014966,5.034443e+06,116.28400,237.436050,184.0,0.243948,-5.663757,4.852265,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.543433,9.080726,POINT (506302.0131994876 5043324.971737838),506302.013199,5.043325e+06,157.51700,161.693850,179.0,0.271845,-0.290116,0.709884,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.520009,9.512221,POINT (540004.0021918486 5040847.0366410855),540004.002192,5.040847e+06,129.02800,246.535260,183.0,0.256281,-0.404723,1.239259,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.478996,9.235491,POINT (518404.99701127905 5036189.993137122),518404.997011,5.036190e+06,117.15800,89.248320,177.0,0.213963,-0.191070,0.804963,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.470499,9.197460,POINT (515434.9718547216 5035237.998363922),515434.971855,5.035238e+06,119.07100,287.122600,183.0,0.124153,-0.100218,0.187807,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.526551,8.736497,POINT (479423.03297180997 5041480.01434023),479423.032972,5.041480e+06,144.81100,281.919560,182.0,0.261740,-0.582216,-0.586305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45.517822,8.766562,POINT (481767.99140634644 5040502.978905675),481767.991406,5.040503e+06,136.53800,248.617870,181.0,0.871315,0.153436,0.069513,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
45.526473,9.515980,POINT (540292.9619092605 5041567.050211332),540292.961909,5.041567e+06,133.11700,37.859215,182.0,0.304025,-4.562784,1.913168,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
#remove unused columns
pm10_data = pm10_data.drop(["sensor_id"], axis=1)
meteo_data = meteo_data.drop(["stationID", "hydrometric_level"], axis=1)
topo_data = topo_data.drop(["geometry"], axis=1)

#round coordinates to 6 decimal places
pm10_data = pm10_data.round({'lat': 6, 'lng': 6})
meteo_data = meteo_data.round({'lat': 6, 'lng': 6})
topo_data = topo_data.round({'lat': 6, 'lng': 6})

In [7]:
#merge all the datasets
#merge pm10 and meteo
pm10_training = pd.merge(meteo_data, pm10_data, how='outer', on=['lat', 'lng', 'date'])

#merge with topo
pm10_training = pd.merge(pm10_training, topo_data, how='outer', on=['lat', 'lng'])

pm10_training.columns

Index(['date', 'lat', 'lng', 'temperature', 'precipitation', 'humidity',
       'global_radiation', 'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW', 'pm_10',
       'utm_x', 'utm_y', 'dtm_milan', 'aspect', 'hillshade', 'ndvi_2019',
       'plan_curvature', 'profile_curvature', 'water_distance', 'slope', 'spi',
       'tri', 'twi', 'densita_popolazione', 'main_road_distance',
       'building_height', 'geo_0', 'geo_1', 'geo_2', 'geo_3', 'geo_4', 'geo_5',
       'geo_6', 'lc_11', 'lc_12', 'lc_14', 'lc_21', 'lc_22', 'lc_23', 'lc_31',
       'lc_32', 'lc_33', 'lc_41', 'lc_51'],
      dtype='object')

In [1]:
pm10_training

NameError: name 'pm10_training' is not defined

In [9]:
#Interpolating missing data
#start_date = date(2016,1,1)
#end_date = date(2022,12,31)
variable_list_NN = ['temperature', 'humidity', 'global_radiation','pm_10',
                'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW']
#variable_list_NN = ['temperature']

variable_list_IDW = ['precipitation']
#variable_list_IDW = []

inter_training = pm10_training.copy()
inter_training['date'] = pd.to_datetime(inter_training['date'],  format="%Y-%m-%d")
inter_training = inter_training.sort_values(by='date')

initial_date = inter_training.iloc[0].date
end_date = inter_training.iloc[-1].date
date_range = [initial_date, end_date]
print(date_range)

for var_name in variable_list_NN:
    print(f'-----------------------------{var_name}---------------------------------')
    interp.single_NN(inter_training, var_name, date_range)
    
for var_name in variable_list_IDW:
    print(f'-----------------------------{var_name}---------------------------------')
    interp.single_IDW_new(inter_training, var_name, date_range)

[Timestamp('1989-01-01 00:00:00'), Timestamp('2023-02-05 00:00:00')]
-----------------------------temperature---------------------------------
1989-01-01 00:00:00 2023-02-05 00:00:00
error in 1990-01-01 00:00:00

KeyboardInterrupt:

In [ ]:
inter_training

In [ ]:
complete_training = inter_training.dropna()

In [ ]:
#calculate if the pm10 daily threshold is exceeded in a separate column
"""
Pollutant   daily     exceedances per year
PM10        50        35
"""
pm10_daily_threshold = 50 #ug/m3
complete_training['exc'] = np.where(complete_training['pm_10'].gt(pm10_daily_threshold), 1, 0)

In [ ]:
complete_training.to_csv('../../data/milano_training_data/pm10_training_data.csv')

In [ ]:
"""----------------------------------------------------------------------------------------"""

In [ ]:
complete_training = pd.read_csv('../../data/milano_training_data/pm10_training_data.csv', index_col=0)
complete_training['date'] = pd.to_datetime(complete_training['date'],  format="%Y-%m-%d")
complete_training = complete_training.round({'lat': 6, 'lng': 6})

In [ ]:
initial_year = 2016
end_year = 2021
years = range(initial_year, end_year+1)
months = [1,2,3,4,5,6,7,8,9,10,11,12]

training_per_month = {}
training_df = complete_training.loc[
    (complete_training['date'].dt.year >= initial_year) & 
    (complete_training['date'].dt.year <= end_year)
]
training_df = training_df.assign(
    year=training_df['date'].dt.year, 
    month=training_df['date'].dt.month
)
training_df.columns

In [ ]:
#Prepare the monthly training data
initial_year = 2016
end_year = 2021
years = range(initial_year, end_year+1)
months = [1,2,3,4,5,6,7,8,9,10,11,12]

training_per_month = {}
training_df = complete_training.loc[
    (complete_training['date'].dt.year >= initial_year) & 
    (complete_training['date'].dt.year <= end_year)
]
training_df = training_df.assign(
    year=training_df['date'].dt.year, 
    month=training_df['date'].dt.month
)
training_df = training_df.drop(['exc','year'], axis=1)

for month in months:
    temp_df = training_df.loc[training_df['date'].dt.month == month]
    temp_df = temp_df.groupby(['month','lat','lng']).mean(numeric_only=True).reset_index()
    #temp_df = temp_df.drop(['year'])
    training_per_month[month] = temp_df.copy()

In [ ]:
for month in months:
    training_per_month[month].to_csv(f'../../data/milano_training_data/pm_10_training_months/pm10_training_month_{month}.csv')

In [ ]:
"""----------------------------------------------------------------------------------------"""
#generate the data for the susceptibility maps in raster format

In [ ]:
for month in months:
    training_per_month[month].to_csv(f'../../data/milano_training_data/pm_10_training_months_rasters/pm10_training_month_{month}.csv')